#version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hotel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./certificates:/app/certificates
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hotel_keys
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_USER=
      - SMTP_PASSWORD=
      - EMAILS_FROM_EMAIL=ayoubenmbarek@gmail.com
      - EMAILS_FROM_NAME=Your Hotel
      - FRONTEND_URL=http://localhost:3000
      - PASS_BASE_URL=https://5a68-2a01-e0a-159-2b50-5c47-ed09-6b4d-d45f.ngrok-free.app/api/v1/passes
    depends_on:
      - db
      - mailhog
    networks:
      - hotel_network
    restart: always

  db:
    image: postgres:14
    container_name: hotel-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hotel_keys
    ports:
      - "5432:5432" # Update posrt to avoid conflict with local postgresl db
    networks:
      - hotel_network
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: hotel-mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - hotel_network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hotel-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=https://5a68-2a01-e0a-159-2b50-5c47-ed09-6b4d-d45f.ngrok-free.app/api/v1
    depends_on:
      - backend
    networks:
      - hotel_network
    restart: always

  adminer:
    image: adminer
    container_name: hotel-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - hotel_network
    restart: always

networks:
  hotel_network:
    driver: bridge

volumes:
  postgres_data:
