"""Initial migration

Revision ID: 0066505e63cc
Revises: a1c2c0cc4e1b
Create Date: 2025-02-28 15:23:41.027352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0066505e63cc'
down_revision = 'a1c2c0cc4e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
