"""Initial migration

Revision ID: 015f76825bf9
Revises: 95b5d8667913
Create Date: 2025-03-16 23:57:49.688634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015f76825bf9'
down_revision = '95b5d8667913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
