"""Initial migration

Revision ID: 019f73384292
Revises: 568a3f366afc
Create Date: 2025-03-16 20:37:03.332095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019f73384292'
down_revision = '568a3f366afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
