"""Initial migration

Revision ID: 111b574079eb
Revises: 181bdad62aa5
Create Date: 2025-03-23 03:28:32.500656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111b574079eb'
down_revision = '181bdad62aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
