"""Initial migration

Revision ID: 1137aa12736f
Revises: 7b0f666928e3
Create Date: 2025-03-23 01:23:25.318064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1137aa12736f'
down_revision = '7b0f666928e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
