"""Initial migration

Revision ID: 181bdad62aa5
Revises: fc29020bb1e8
Create Date: 2025-03-23 03:03:06.435509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181bdad62aa5'
down_revision = 'fc29020bb1e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
