"""Initial migration

Revision ID: 18d9a8511852
Revises: ba988b44eb82
Create Date: 2025-03-03 19:55:59.508282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d9a8511852'
down_revision = 'ba988b44eb82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
