"""Initial migration

Revision ID: 1e6463a12067
Revises: c87e23da9cb4
Create Date: 2025-02-28 14:43:55.153584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6463a12067'
down_revision = 'c87e23da9cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
