"""Initial migration

Revision ID: 20835d539e59
Revises: a3677a0a0bbe
Create Date: 2025-02-28 01:05:24.083438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20835d539e59'
down_revision = 'a3677a0a0bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
