"""Initial migration

Revision ID: 218f21faf66e
Revises: f4be49747704
Create Date: 2025-02-28 21:36:26.111167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218f21faf66e'
down_revision = 'f4be49747704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
