"""Initial migration

Revision ID: 2b5258446b5b
Revises: 60786d07d435
Create Date: 2025-03-20 00:51:06.625626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5258446b5b'
down_revision = '60786d07d435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
