"""Initial migration

Revision ID: 2b890d65b302
Revises: c7d32ebb6349
Create Date: 2025-02-28 01:13:37.709266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b890d65b302'
down_revision = 'c7d32ebb6349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
