"""Initial migration

Revision ID: 30aabafb6fe2
Revises: 90349e7f309e
Create Date: 2025-02-28 01:02:17.038359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aabafb6fe2'
down_revision = '90349e7f309e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
