"""Initial migration

Revision ID: 37bed1a6ef66
Revises: 015f76825bf9
Create Date: 2025-03-19 23:31:08.690447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bed1a6ef66'
down_revision = '015f76825bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
