"""Initial migration

Revision ID: 410e49139ec8
Revises: 3191052f661b
Create Date: 2025-02-28 00:52:08.089074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410e49139ec8'
down_revision = '3191052f661b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
