"""Initial migration

Revision ID: 413e1fa6d1d3
Revises: 741148b790fe
Create Date: 2025-03-03 21:52:04.168151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413e1fa6d1d3'
down_revision = '741148b790fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
