"""Initial migration

Revision ID: 446f996bc97c
Revises: dde5d5944110
Create Date: 2025-03-10 23:05:29.283950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446f996bc97c'
down_revision = 'dde5d5944110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
