"""Initial migration

Revision ID: 5173b397e3a7
Revises: ecc676badbe3
Create Date: 2025-03-15 10:28:00.666997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5173b397e3a7'
down_revision = 'ecc676badbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
