"""Initial migration

Revision ID: 559103383c13
Revises: 3ec778d80ae1
Create Date: 2025-02-28 00:36:51.390883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559103383c13'
down_revision = '3ec778d80ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
