"""Initial migration

Revision ID: 561dc4ef6b3b
Revises: acffadcfc1a6
Create Date: 2025-03-21 15:22:07.718680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561dc4ef6b3b'
down_revision = 'acffadcfc1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
