"""Initial migration

Revision ID: 568a3f366afc
Revises: 5173b397e3a7
Create Date: 2025-03-15 11:36:29.855260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568a3f366afc'
down_revision = '5173b397e3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
