"""Initial migration

Revision ID: 5a3878301243
Revises: 553ba9fa36fa
Create Date: 2025-03-06 22:42:31.726447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3878301243'
down_revision = '553ba9fa36fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
