"""Initial migration

Revision ID: 60786d07d435
Revises: 37bed1a6ef66
Create Date: 2025-03-20 00:41:15.138957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60786d07d435'
down_revision = '37bed1a6ef66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
