"""Initial migration

Revision ID: 61269082c632
Revises: a2ee43ef0038
Create Date: 2025-03-23 02:03:05.999067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61269082c632'
down_revision = 'a2ee43ef0038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
