"""Initial migration

Revision ID: 685b630ca099
Revises: 561dc4ef6b3b
Create Date: 2025-03-21 15:38:43.638083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685b630ca099'
down_revision = '561dc4ef6b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
