"""Initial migration

Revision ID: 73cd78d7b427
Revises: ed26dda073cc
Create Date: 2025-03-05 20:14:31.238913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cd78d7b427'
down_revision = 'ed26dda073cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
