"""Initial migration

Revision ID: 741148b790fe
Revises: 18d9a8511852
Create Date: 2025-03-03 21:49:43.732348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741148b790fe'
down_revision = '18d9a8511852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digitalkey', sa.Column('auth_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digitalkey', 'auth_token')
    # ### end Alembic commands ###
