"""Initial migration

Revision ID: 7b0f666928e3
Revises: 685b630ca099
Create Date: 2025-03-23 01:08:43.525028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0f666928e3'
down_revision = '685b630ca099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
