"""Initial migration

Revision ID: 7bb1aefa8a0f
Revises: ed1dccd16321
Create Date: 2025-02-28 01:07:40.479961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb1aefa8a0f'
down_revision = 'ed1dccd16321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
