"""Initial migration

Revision ID: 7e0d88eb679a
Revises: 446f996bc97c
Create Date: 2025-03-10 23:16:18.438241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0d88eb679a'
down_revision = '446f996bc97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
