"""Initial migration

Revision ID: 85d81be14afa
Revises: 218f21faf66e
Create Date: 2025-02-28 21:52:55.864301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d81be14afa'
down_revision = '218f21faf66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
