"""Add auth_token to DigitalKey and create DeviceRegistration table

Revision ID: 878c46fce131
Revises: 413e1fa6d1d3
Create Date: 2025-03-03 22:57:27.735234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878c46fce131'
down_revision = '413e1fa6d1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
