"""Add auth_token to DigitalKey and create DeviceRegistration table

Revision ID: 8a12070ea5e2
Revises: 878c46fce131
Create Date: 2025-03-03 23:05:34.387115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a12070ea5e2'
down_revision = '878c46fce131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
