"""Initial migration

Revision ID: 8f1ec5abe96e
Revises: 019f73384292
Create Date: 2025-03-16 20:40:56.818362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1ec5abe96e'
down_revision = '019f73384292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
