"""Initial migration

Revision ID: 90349e7f309e
Revises: 410e49139ec8
Create Date: 2025-02-28 01:01:06.556083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90349e7f309e'
down_revision = '410e49139ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
