"""Initial migration

Revision ID: 914bcafc0334
Revises: b6e6e6b5aad6
Create Date: 2025-03-06 23:25:11.423874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914bcafc0334'
down_revision = 'b6e6e6b5aad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
