"""Initial migration

Revision ID: 93fd925b2789
Revises: c81b2be45ca2
Create Date: 2025-02-28 22:35:50.243123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fd925b2789'
down_revision = 'c81b2be45ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
