"""Initial migration

Revision ID: 95b5d8667913
Revises: 8f1ec5abe96e
Create Date: 2025-03-16 21:01:20.995826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b5d8667913'
down_revision = '8f1ec5abe96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
