"""Initial migration

Revision ID: a095773d18db
Revises: ba8aec4ec361
Create Date: 2025-03-15 09:13:38.845551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a095773d18db'
down_revision = 'ba8aec4ec361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
