"""Initial migration

Revision ID: a1c2c0cc4e1b
Revises: 1e6463a12067
Create Date: 2025-02-28 14:50:34.088501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c2c0cc4e1b'
down_revision = '1e6463a12067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
