"""Initial migration

Revision ID: a2ee43ef0038
Revises: 1137aa12736f
Create Date: 2025-03-23 01:25:07.856839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ee43ef0038'
down_revision = '1137aa12736f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
