"""Initial migration

Revision ID: a3677a0a0bbe
Revises: 30aabafb6fe2
Create Date: 2025-02-28 01:04:13.686991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3677a0a0bbe'
down_revision = '30aabafb6fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
