"""Initial migration

Revision ID: acffadcfc1a6
Revises: b81f4f856afc
Create Date: 2025-03-21 15:13:18.570053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acffadcfc1a6'
down_revision = 'b81f4f856afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
