"""Initial migration

Revision ID: b2906df0d999
Revises: 7e0d88eb679a
Create Date: 2025-03-11 00:03:10.297979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2906df0d999'
down_revision = '7e0d88eb679a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
