"""Initial migration

Revision ID: b4d36cc6d1a1
Revises: 93fd925b2789
Create Date: 2025-02-28 22:48:42.429345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d36cc6d1a1'
down_revision = '93fd925b2789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
