"""Initial migration

Revision ID: b6e6e6b5aad6
Revises: 5a3878301243
Create Date: 2025-03-06 23:11:36.748920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e6e6b5aad6'
down_revision = '5a3878301243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
