"""Initial migration

Revision ID: b81f4f856afc
Revises: 2b5258446b5b
Create Date: 2025-03-21 14:40:36.179066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81f4f856afc'
down_revision = '2b5258446b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
