"""Initial migration

Revision ID: ba8aec4ec361
Revises: b2906df0d999
Create Date: 2025-03-15 00:40:43.044782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8aec4ec361'
down_revision = 'b2906df0d999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
