"""Initial migration

Revision ID: ba988b44eb82
Revises: ed83c02e123d
Create Date: 2025-03-03 19:49:27.276238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba988b44eb82'
down_revision = 'ed83c02e123d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
