"""Initial migration

Revision ID: c7d32ebb6349
Revises: 7bb1aefa8a0f
Create Date: 2025-02-28 01:10:45.957348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d32ebb6349'
down_revision = '7bb1aefa8a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
