"""Initial migration

Revision ID: c81b2be45ca2
Revises: 85d81be14afa
Create Date: 2025-02-28 22:28:30.997719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81b2be45ca2'
down_revision = '85d81be14afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
