"""Initial migration

Revision ID: c87e23da9cb4
Revises: 2b890d65b302
Create Date: 2025-02-28 14:15:40.398957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87e23da9cb4'
down_revision = '2b890d65b302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
