"""Initial migration

Revision ID: dde5d5944110
Revises: 914bcafc0334
Create Date: 2025-03-10 22:44:41.158943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde5d5944110'
down_revision = '914bcafc0334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
