"""Initial migration

Revision ID: ecc676badbe3
Revises: a095773d18db
Create Date: 2025-03-15 09:25:49.763999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc676badbe3'
down_revision = 'a095773d18db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
