"""Initial migration

Revision ID: ed1dccd16321
Revises: 20835d539e59
Create Date: 2025-02-28 01:06:18.129048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1dccd16321'
down_revision = '20835d539e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
