"""Add auth_token to DigitalKey and create DeviceRegistration table

Revision ID: ed26dda073cc
Revises: 8a12070ea5e2
Create Date: 2025-03-03 23:05:43.431954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed26dda073cc'
down_revision = '8a12070ea5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
