"""Initial migration

Revision ID: ed83c02e123d
Revises: 5e609f1f6783
Create Date: 2025-03-03 19:40:00.258748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed83c02e123d'
down_revision = '5e609f1f6783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
