"""Initial migration

Revision ID: f4be49747704
Revises: 0066505e63cc
Create Date: 2025-02-28 16:54:22.165939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4be49747704'
down_revision = '0066505e63cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
