"""Initial migration

Revision ID: f93c6a219ba0
Revises: b4d36cc6d1a1
Create Date: 2025-03-02 00:09:42.897979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93c6a219ba0'
down_revision = 'b4d36cc6d1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
