"""Initial migration

Revision ID: fc29020bb1e8
Revises: 61269082c632
Create Date: 2025-03-23 02:36:01.182354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc29020bb1e8'
down_revision = '61269082c632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
